services:
  - type: web
    name: kairos-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: WALLET_ADDRESS
        value: 8UQuZwPYEPnEhVvaodMmEjm3HcNMBRRuDd13jKVdBZqG
      - key: PHANTOM_KEY_BASE58
        sync: false  # Cette variable doit être configurée manuellement dans le dashboard Render
